### ISSUE TITLE
include *.md & <marked> </marked> no parse html code

### ISSUE THREAD

**Issue by amily4555** [Hypercubed/angular-marked#10]
set(scope.marked || element.text() || ''); 
=> change to
set(scope.marked || element.html() || '');

**Comment by Hypercubed** [comment]
I tried this previously... it doesn't work as expected.

**Comment by ajielee** [comment]
I got the same problem, and I use the README.md of this project to test, the result is:

1. with `set(scope.marked || element.text() || ''); `
![img1](http://i.imgur.com/4WBFQsD.png)

2. with `set(scope.marked || element.html() || '');`
![img2](http://i.imgur.com/hUrBnXw.png)

Is there any solution yet?

**Comment by Hypercubed** [comment]
Use an ng-include or a scope variable instead of inline markdown.  Unfortunately, as you can see in your example, `element.html` does't work either.

**Comment by ajielee** [comment]
I've tested several different types of code: CSS, Sass, JS, HTML, XML, Java, Python, C++
And the results are:
1. It works: CSS, Sass, JS, Java, Python
2. It doesn't work: HTML, XML, C++

**Comment by Hypercubed** [comment]
@amily4555 and @ajielee ,  I'm sorry I didn't understand this issue until now.  I thought the issue was only happening when the code was inline and as @ajielee pointed out changing `element.text()` to `element.html()` doesn't fix the issue.  Now with the latest version (v0.0.20) you should use the `src` attribute instead of ng-include.  This should interpret html code in the included markdown file correctly.  If you must have the markdown inline use an `text/ng-template` script tag.  Please let me know if this solves your issue.

**Comment by ajielee** [comment]
@Hypercubed I've tested the latest version, but the issue exists as before.

**Comment by Hypercubed** [comment]
Can you share how you are using the directive?  Here is a plunker showing how to avoid code block issues using the src attribute: http://plnkr.co/edit/0y8G4E?p=preview

**Comment by ajielee** [comment]
@Hypercubed With your example, it works perfectly!!!

My code before is like this: 

```html
<div marked ng-include="'markdowns/about-me_cn.md'" class="markdown-content" ng-show="language === 'cn'" ng-hide="language !== 'cn'"></div>
```

And after modification it becomes:
```html
<marked src="'markdowns/about-me_cn.md'" class="markdown-content" ng-show="language === 'cn'" ng-hide="language !== 'cn'"></marked>
```

I've tested all types of code that did work before, now they look normally:

HTML:
![HTML](http://i.imgur.com/yd8eS6V.png)

XML:
![XML](http://i.imgur.com/UluRWA8.png)

C++:
![C++](http://i.imgur.com/Wpg94no.png)

Thanks a million!!!

**Comment by Hypercubed** [comment]
Great!!  Thank you for letting me know about this issue.  It is unfortunate that I didn't understand the OPs issue for 7 months.  Closing.
