### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by qraynaud** [Hypercubed/angular-marked#13]
This would be great if this module could be published on NPM too. The angular & angular-ui teams a publishing on NPM so I think this makes sense.

I'm trying to move away from bower as much as possible and NPM appeals a lot to me.

**Comment by Hypercubed** [comment]
I understand, I'll have to look into this.  I haven't adopted NPM for front yet myself (leaning more towards JSPM) so I am not exactly sure how this would work.

**Comment by qraynaud** [comment]
I can maybe give at least some inputs about this:
- you need a `package.json` file that is probably the same for JSPM
- you need a `.npmignore` file listing every file not to publish
- you can use `npm pack` to create a tgz like the one that will be published to check the packaging is correct
- you need an NPM user (you can create one on the official website if you don't have any)
- you can login to NPM in the CLI using `npm login`
- after that `npm publish` should do the trick

I have a last remark to do: I'm also believing JSPM is better for front packages than NPM. But being also a node dev, I don't want to use 2 tools to achieve the same purpose since it is making everything more difficult.

The NPM team has more than once stated it knew NPM was not perfect for this use case and that they wanted to make NPM the registry for JS at large. I believe they have the traction to achieve it and that it is a good goal. I think we should help them. On their roadmap the front problem is specifically stated for fixing: https://github.com/npm/npm/wiki/Roadmap (point 4).

Hope I was of some help.

**Comment by Hypercubed** [comment]
Thank you.  I published to npm without trouble.  What I don't know is how this will work on the users end.  Can you please git it a try and let me know?

**Comment by qraynaud** [comment]
sure

**Comment by qraynaud** [comment]
It works as intended. I would also advise you to add to `.npmignore` the followings:

```
docs-template
example
test
.npmignore
.travis.yml
bower.json
gruntfile.js
karma.conf.js
todo.md
```

The rationale is that they are not needed in the package as far as I know.

Thanks a lot!

**Comment by Hypercubed** [comment]
If all that is needed is `package.json` and the js files.  I could setup `.npmignore' like this (package.json is always included):

```
*
!angular-marked.*
```

**Comment by qraynaud** [comment]
README.md & package.json are also needed

**Comment by Hypercubed** [comment]
Ok done, thank you.

**Comment by qraynaud** [comment]
You're welcome. Thank you too!
