### ISSUE TITLE
Issue while using data binding

### ISSUE THREAD

**Issue by ajielee** [Hypercubed/angular-marked#23]
Hello again, I want to create an online markdown editor while using your lib. 
With data binding, it parser markdown code normally but then it shows up HTML source code directly.
I don't understand what's wrong, can you have a look my code and help? Thank you.

* This is HTML part:

```html
<div class="container-fluid main-div" ng-controller="mainCtrl">
        <div class="row">
            <div class="col-sm-6">
                <h4 class="text-center">Write your markdown code:</h4>
                <div class="well well-input">
                    <textarea ng-model="markdownSource"></textarea>
                </div>
            </div>
            <div class="col-sm-6">
                <h4 class="text-center">Then your content will show up here:</h4>
                <div class="well">
                    {{ markdownDisplay }}
                </div>
            </div>
        </div>
    </div>
```

* This is js part:

```js
var ngMarkdownEditor = angular.module("ngMarkdownEditor", ['hc.marked'])
 .config(['markedProvider', function(markedProvider) {
     // configuration for angular-marked
     markedProvider.setOptions({
         gfm: true,
         tables: true,
         highlight: function (code) {
             return hljs.highlightAuto(code).value;
         }
     });
     markedProvider.setRenderer({
         link: function(href, title, text) {
             return "<a href='" + href + "' title='" + title + "' target='_blank'>" + text + "</a>";
         }
     });

 }]);
ngMarkdownEditor.controller('mainCtrl', ['$scope', 'marked', function($scope, marked) {
    $scope.markdownSource = "";
    $scope.$watch('markdownSource', function() {
        $scope.markdownDisplay = marked($scope.markdownSource);
    });
}]);
```

* What it looks like when it runs:

![img](http://i.imgur.com/ykDY2RF.png)

**Comment by Hypercubed** [comment]
The `marked` function returns the rendered markdown as text.  Therefore the html template tag `              {{ markdownDisplay }}` will display the html as text, not rendered by DOM.  Either use `ng-bind-html` (`<div class="well" ng-bind-html="markdownDisplay"></div>`) or the markdown directive:  `<div class="well" marked="markdownSource"></div>`.

**Comment by ajielee** [comment]
@Hypercubed I've tested these two solution and the second one works, thanks for your help! 

for the first one, it causes this error:

Error: $sce:unsafe
Require a safe/trusted value
```
Attempting to use an unsafe value in a safe context.
```

**Comment by Hypercubed** [comment]
See the details on `ngSanitize` here:  https://docs.angularjs.org/api/ng/directive/ngBindHtml

If you are using the first method (`ng-bind-html`)  then you probably don't needed angular-marked at all, just use marked directly.

**Comment by ajielee** [comment]
OK, thank you!

**Comment by Hypercubed** [comment]
NP
