### ISSUE TITLE
Apply marked in javascript

### ISSUE THREAD

**Issue by BannedForLife** [Hypercubed/angular-marked#24]
I have a value attached to an ng-model. I would like this value to be run through marked. Something like this.

JS:
<code>var text = "&lt;script&gt;alert('hello scriptio')&lt;/script&gt;"
scope.text = marked(text)</code>

HTML:
`<textarea ng-model="text"></textarea>`

Is this possible?

**Comment by Hypercubed** [comment]
Of course. You don't need angular marked for this.   Just used marked. Or see the “as a service” section in the readme.

**Comment by Hypercubed** [comment]
If I misunderstood something please reopen.
