### ISSUE TITLE
scroll-to anchor # when using markdown

### ISSUE THREAD

**Issue by wkjesus** [Hypercubed/angular-marked#30]
i found an issue using angular-marked for generatin markdown to html, when use de directive, i wont work, i found a solution, adding this line.
$compile(element.contents())(scope); on the section of directive marked in function set... i hope this help some one, and hope can iclude this solution, review and test if is thebest... greetings !!!

**Comment by Hypercubed** [comment]
Can you explain what issue you are having?  What doesn't work?

**Comment by Hypercubed** [comment]
Compiling the content after markdown is included causes code blocks to break in some cases.  Close for now.  If you can better explain what issues you are having with scroll-to please reopen.  Thanks.
