### ISSUE TITLE
issue with marked.js#0.3.5

### ISSUE THREAD

**Issue by ajielee** [Hypercubed/angular-marked#31]
I got an issue when I updated marked.js to version 0.3.5 with bower, and then angular-marked.js#0.0.21 doesn't work any more. But when I checked in console, there wasn't any error. Now I rolled back to marked.js#0.3.3, then angular-marked.js#0.0.21 works again. I haven't got a clue if there was a conflict between these two libraries or not.

My usage of  angular-marked.js: 

```js
$scope.$watch('markdownSource', function() {
  $scope.markdownDisplay = marked($scope.markdownSource);
});
```

```html
<textarea class="text-div" ng-show="showEditor" ng-model="markdownSource" placeholder="Let's write something here..."></textarea>
<div class="markdown-div" ng-show="showViewer" marked="markdownSource"></div>
```

**Comment by johnwebbcole** [comment]
I'm seeing this as well.  0.3.3 works, 0.3.4 does not.  No errors other than the markdown source is rendered inside a single `<p>` tag.

**Comment by ascholz81** [comment]
I see this as well.  Marked 0.3.3 works well, but 0.3.5 has issues.  I know this is mainly a wrapper to the marked project, however maybe you should consider tying your version to a specific version of marked to ensure continued functionality.  This breakage was a surprise to my project that took a while to surface.

Currently I'm using it for mainly headings.
"##My Heading"
With v0.35 I have to change the string to "## My Heading"

**Comment by ascholz81** [comment]
My issue was resolved by the marked project owner.  Marked was not following GFM correctly.  They have updated to requiring a space after the # for headings.

**Comment by ajielee** [comment]
@ascholz81 Did marked.js release the new version yet?

**Comment by Hypercubed** [comment]
@ajielee @johnwebbcole The new version of marked requires a space after the hashes (https://github.com/chjj/marked/issues/642).  Is this your issue?

**Comment by Hypercubed** [comment]
@ajielee Why do you have a `$scope.$watch` statement in your example?  If you are using the directive you don't need to call `marked` directly.

**Comment by ajielee** [comment]
@Hypercubed Yes, that's the reason why I got the problem. But I don't agree with the GFM style, so I still hold marked.js#0.3.3. Thank you.

**Comment by ajielee** [comment]
@Hypercubed Sorry for that block of code, which I forgot to delete.

**Comment by Hypercubed** [comment]
@chjj recommends:

```
marked.Lexer.rules.gfm.heading = marked.Lexer.rules.normal.heading;
```

 You might be able to do something like this using the [setRenderer method](https://github.com/Hypercubed/angular-marked#override-rendered-markdown-links).

**Comment by chjj** [comment]
GFM does not support headings such as: "##heading". Only the original markdown implementation does. Like @Hypercubed mentioned, either overwrite the rules or use `gfm: false`.

If we were to change the GFM rules to accept headings like that, there would be another camp of people posting issues about incohesiveness with GFM, unfortunately. Personally, I don't think it's a big deal, but we're trying more to stick to GFM, however inconvenient it may be.
