### ISSUE TITLE
Convert from html back to markdown?

### ISSUE THREAD

**Issue by kristyoverton** [Hypercubed/angular-marked#33]
Is there a way to convert my html back into markdown? I'm not seeing anything, but it never hurts to ask.

**Comment by Hypercubed** [comment]
I had a professor that used to say... "Don't hesitate too much to ask questions, hesitate a little, but not too much."

angular-marked and marked itself will not convert HTML to markdown.  Perhaps try https://github.com/domchristie/to-markdown.
