### ISSUE TITLE
Compile after setting html

### ISSUE THREAD

**Issue by aakilfernandes** [Hypercubed/angular-marked#36]
I updated a local fork to $compile after setting the html. I didn't do a PR because it caused all the tests to fail for some reason.

https://github.com/SafeMarket/angular-marked/commit/48e359c5e23ae7aea9c17b31d6ae406c048ee0d4

**Comment by Hypercubed** [comment]
This has been tried a couple of times in a few ways but always lead to issues.  I'm planning to look at it again sometime...

**Comment by Hypercubed** [comment]
I think the only way to get this to work is only compile the non-script parts of the html output.  Otherwise you need to escape all code blocks to prevent angular from compiling them.  Closing for now.
