### ISSUE TITLE
Is it possible to configure the renderer based on the page location ?

### ISSUE THREAD

**Issue by kcheick** [Hypercubed/angular-marked#37]
I am trying to override the link generated by the markdown renderer to make them relative to the current page instead of the root page but my only option to do so now is to do it in the config section where i don't have access to the current location of the page. 
IS there a way to configure the renderer in the controller? or any other solution to this problem ?

**Comment by Hypercubed** [comment]
That would be a nice feature.  Maybe the best you can do right now is use the marked service  (or the marked global instance) directly in your controller.

**Comment by xiphiaz** [comment]
+1This feature would be great. 

There is a workaround however - in a run function you can merge your custom renderer with `marked.defaults.renderer`. This is a hack though as it overrides the default renderer functionality, but it does work and is a good stop-gap hack until this feature is implemented.

Example:

app.run(function(marked, someService) {

    var newRenderer = {
        link: function(href, title, text){
             return someService.buildLink(href, text);
        }
    };

    marked.defaults.renderer = angular.merge(marked.defaults.renderer, newRenderer)
});

**Comment by Hypercubed** [comment]
@kcheick @xiphiaz I'm going to close this for now.  If either of you can figure out how to do this in a reasonable generic way please submit a PR.  Thank you.
