### ISSUE TITLE
Is it Possible to get only text?

### ISSUE THREAD

**Issue by arg20** [Hypercubed/angular-marked#38]
I have a copy to clipboard feature in which I have a fragment in the form of: 
`my **styled up** fragment `

but I need to get rid of the markdown markup so as to end with:
`my styled up fragment`

so that I can feed that to a copy to clipboard function, is this possible?

**Comment by Hypercubed** [comment]
I'm not sure I understand.  If you render markdown to HTML in the DOM you can use `innerTEXT`.

**Comment by arg20** [comment]
Ok, just wondering if it's possible with a function call cause I don't really need to render it on the DOM at that point. Like I basically just want to strip out markdown and only get the text (I'm not within a directive but rather within an angular service)

**Comment by Hypercubed** [comment]
So the marked service is really just the [marked library](https://github.com/chjj/marked).  It converts markdown to HTML.  I don't think it is within it's scope to strip markdown.

That said you might be able to do something like this:  

```js
var html = marked('## test\n\n\t\tHello');
var text = $(html).text();

console.log(text);
```

(I'm using jQuery for simplicity, but possible without jQuery I'm sure).

**Comment by Hypercubed** [comment]
Closing, reopen if you need more help.
