### ISSUE TITLE
How to mark a variable ?

### ISSUE THREAD

**Issue by tiberiucorbu** [Hypercubed/angular-marked#39]
I have seen no docs on how to render markdown dynamically. Is it possible ?

**Comment by Hypercubed** [comment]
Not sure what you mean.  Like this:  http://hypercubed.github.io/angular-marked/#/api/hc.marked.directive:marked#example_bind-to-a-scope-variable

**Comment by tiberiucorbu** [comment]
Yes exactly, sorry for bugging you.

**Comment by Hypercubed** [comment]
NP
