### ISSUE TITLE
How to show {{}} code in markdown

### ISSUE THREAD

**Issue by erguotou520** [Hypercubed/angular-marked#40]
I wrote a markdown text with this.
`{{exception | filter:arg[:arg1:arg2...:argN]}}`
But angularjs will listen it and give me an error like this.
`http://errors.angularjs.org/1.4.7/$parse/syntax?p0=%3A&p1=not%20a%20primary%20expression&p2=24&p3=exception%20%7CNaNilter%3Aarg%5B%3Aarg1%3Aarg2...%3AargN%5D&p4=%3Aarg1%3Aarg2...%3AargN%5D`
How to show `{{}}` code safely in angular-marked?

**Comment by Hypercubed** [comment]
Try using the template method (https://github.com/Hypercubed/angular-marked#use-as-a-directive).  Something like this:

```js
<script type="text/ng-template" id="tpl.md">
  ## Markdown

      {{exception | filter:arg[:arg1:arg2...:argN]}}
</script>

<div marked src="'tpl.md'"></div>
```

**Comment by Hypercubed** [comment]
Please let me know if that works.

**Comment by erguotou520** [comment]
Yeah, it works by using the `script` method. But not work in directive like below.
```
<marked>
{{exception | filter:arg[:arg1:arg2...:argN]}}
</marked>
```

**Comment by Hypercubed** [comment]
That will never work with code blocks.  You need to use the `script` template.

**Comment by erguotou520** [comment]
Thanks. I got it.
