### ISSUE TITLE
Publish the build version on NPM.

### ISSUE THREAD

**Issue by qraynaud** [Hypercubed/angular-marked#42]
Right now it does not work anymore to include the lib/angular-marked.js file published in NPM in the browser.

I'm using NPM to manage front dependencies but I would like to have build version in the package.

Is it possible for you to fix this?

Thanks a lot!

**Comment by Hypercubed** [comment]
Sure, I can do that.  But can I ask...  most npm packages do not include the build files, how are you managing other packages?  Would it be better in the long run for you to include browserify (or equivalent) in your build tools?  It is helpful for me to understand how people are using this package.   Thank you.

**Comment by qraynaud** [comment]
Well, all other packages (including angular files) I'm using (except lodash) do provide « packaged versions » in dist.

I mean there is sometimes a min file (like for angular.js wich provides both) but you can at least find a file with all the src files concatenated in them and protected by an UMD or something like that. If they are not minified I do the minification myself for the production env.

The thing that is always possible is to include the files « as is » for the dev env without having an error raised in the console (here caused by module.exports = "…").

For the record, right now I need bower for only two packages: lodash and angular-marked. I would love to get rid of bower though…

**Comment by Hypercubed** [comment]
Thank you for the feedback.  It is difficult to know exactly all ways a package will be used.

Version 1.0.1 now includes the browserify version.  Please let me know if you have issues.

**Comment by qraynaud** [comment]
Thanks a lot to you for your reactivity! I'll close this and reopen it if I find something "wrong".

Thanks again!
