### ISSUE TITLE
Displaying custom error information if the markdown document is missing

### ISSUE THREAD

**Issue by kalyanvgopal** [Hypercubed/angular-marked#44]
First of angular-marked is a very handy directive. Thanks for that.
I am using the following in the code.
` <div marked src="vm.document"> </div> `
I want to display a custom error partial if the vm.document is missing from the document file store. Do you have a suggestion or do you think marked directive needs a change? I would prefer something like the below.
`<div marked src="vm.document" errSrc="vm.errorTemplate"> </div> `
If you agree i can contribute as well.

**Comment by Hypercubed** [comment]
Hmm....  I think something is missing from your message.

**Comment by kalyanvgopal** [comment]
Sorry. I updated my original post.

**Comment by Hypercubed** [comment]
Sounds resionable.  Maybe add a error callback here:  https://github.com/Hypercubed/angular-marked/blob/master/lib/angular-marked.js#L311

PRs welcome.

**Comment by Hypercubed** [comment]
On second thought... maybe best to add a onError callback?  This callback can handle generating an error message.

**Comment by Hypercubed** [comment]
The ng-include directive dispatches an event on error:  https://github.com/angular/angular.js/blob/master/src/ng/directive/ngInclude.js#L262

**Comment by kalyanvgopal** [comment]
I made the pull request. Please provide your feedback.

**Comment by Hypercubed** [comment]
Merged... thank you.
