### ISSUE TITLE
Problem while loading markdown files with angular-marked

### ISSUE THREAD

**Issue by Jopenergy1212** [Hypercubed/angular-marked#45]
Hi,
I'm sorry, I'm a beginner and I can't find the solution to my problem...

Everything works fine when I use angular-marked as a directive but I'm interested in loading markdown files with the command
`<div marked src="/static/data/documentation/README.md"></div>`
but I get : **"Error: [$parse:syntax] Syntax Error: Token '/' not a primary expression at column 1 of the expression [/static/data/documentation/README.md]"**

And if I remove the first '/' I get another error : 
**"WARNING: Tried to load angular more than once."** and the associated web page is just a mess...

Thx a lot if you have any idea.

**Comment by Jopenergy1212** [comment]
Actually in the second case, index.html is fully reloaded. I only get  a warning message for angular.js but in fact all js files called in index.html are loaded again.

**Comment by Hypercubed** [comment]
Like [ng-include](https://docs.angularjs.org/api/ng/directive/ngInclude) the `src` attribute is an angular expression evaluating to URL.  Try wrapping the url in single quotes like this:

```js
<div marked src="'/static/data/documentation/README.md'"></div>
```

**Comment by Jopenergy1212** [comment]
Yes thank you, I knew it was surely that easy... It works perfectly now, thank you.

**Comment by Hypercubed** [comment]
NP
