### ISSUE TITLE
cant't deal with li>table

### ISSUE THREAD

**Issue by johanninos** [Hypercubed/angular-marked#49]
* skladfjlasdkfj
* asdlfjlasdfj
  
  |aslkdjflsadkf|laksdjflka|
  |--------|---------|

Output:
skladfjlasdkfj
asdlfjlasdfj

|aslkdjflsadkf|laksdjflka| |--------|---------| |dslkfjasldfkj|salkdfjlasdkfj|

**Comment by Hypercubed** [comment]
Have you tried setting the marked config options?  

```
app.config(['markedProvider', function (markedProvider) {
  markedProvider.setOptions({
    gfm: true,
    tables: true
}]);
```

If you are still having issues please reopen.  Thank you.
