### ISSUE TITLE
Possible to hook into markdown content with angular events (ng-click, etc...)

### ISSUE THREAD

**Issue by ggoforth** [Hypercubed/angular-marked#51]
For instance, I want to make all images appear smaller in the rendered markdown, and on click, show the image version in a lightbox.  Is that possible?  The markdown content has `<img ...>` tags that I can parse and render in the controller using the `marked` service, but my attempts to add `ng-click` events have been less than fruitful.

**Comment by ggoforth** [comment]
Basically, what I'm asking is, can I inject my own angular directives INTO the content being parsed (like image tags, links, etc....)

**Comment by Hypercubed** [comment]
Hello,

This has come up a few times.  Unfortunately there is not an easy to get angular directives to run without impacting code blocks.  Theoretically it should be possible to tweak marked's parser to pass non-code block html through angular's $compile but honestly I haven't tried.

Please look at the comment here:  https://github.com/Hypercubed/angular-marked/issues/43#issuecomment-165673163

**Comment by Toilal** [comment]
Simply adding this line of code after markdown parsing do the trick

```
$compile(element.contents())(scope.$parent);
```

I'll open a Pull Request with an option to compile (default to false)

**Comment by Hypercubed** [comment]
Before you get too far look at this comment:  https://github.com/Hypercubed/angular-marked/issues/43#issuecomment-165673163

You need to ensure that only non-code blocks are processed, otherwise it will be impossible to include angular code within the markdown.

**Comment by Toilal** [comment]
I see. I think it would be still possible by injecting [ng-non-bindable](https://docs.angularjs.org/api/ng/directive/ngNonBindable) in marked output of code blocks element.

**Comment by Hypercubed** [comment]
If you can get it to work that would be great.  Maybe tap into the `highlight` or `setRenderer` options.

**Comment by Toilal** [comment]
Pull Request is there. But how can I build the dist files ?

**Comment by Toilal** [comment]
Ho I understand, I just saw there are some npm scripts defined in package.json :)

I need to rebase the Pull Request because i've changed something in karma configuration that is finally not required when using those scripts.

**Comment by Hypercubed** [comment]
Did you exclude code blocks?

**Comment by Toilal** [comment]
Yes, they are excluded by using an internal renderer hook on code. This hook calls the default renderer and wrap it's output in a `<span ng-non-bindable></span>` element.
