### ISSUE TITLE
Creating Id's

### ISSUE THREAD

**Issue by 4tron** [Hypercubed/angular-marked#52]
I am not sure if i am doing something wrong but I cannot get `{#this-is-an-id}` does not work, it just displays the the text to create an ID

**Comment by Hypercubed** [comment]
Do you mean links like this:  `[some text](#sometext)`

**Comment by 4tron** [comment]
No . When creating ID's in the markdown 

https://gist.github.com/micmcg/976172#markdown-plus-h2-with-a-custom-id----------id-goes-here

the ID is not being created and is being displayed as it is written and not parsed as markdown

![err](https://cloud.githubusercontent.com/assets/11210554/13169570/42a3c2fe-d6ef-11e5-9242-a3f26c3f4391.png)

I am not sure if i need to remove auto ID generation, however i do want auto ID generation for most of the titles

**Comment by Hypercubed** [comment]
I think that is not standard markdown.  If it is not available in marked already then you will need to add it there.  Try looking at the marked repo.

**Comment by 4tron** [comment]
Ok will do. Thanks
