### ISSUE TITLE
XSS flaw

### ISSUE THREAD

**Issue by rylyade1** [Hypercubed/angular-marked#54]
Hello,
i was just running test for my application and i discovered a cross site scripting flaw in your library. Here is a [plunker](https://plnkr.co/edit/0cZy8IEsuHjWyVIKFreM?p=preview) which show it. You can see the script ist not printed out as plain text because it is executed. For one reason or the other the script is not executed but if you browse through the html code, you will be able to see the script tag. I will be very gradeful if you could fixed this. 
Thanks.

**Comment by Hypercubed** [comment]
Hello....  Did you see this note in the readme:

Please note: neither this directive nor marked (by default) implement sanitization. As always, sanitizing is necessary for user-generated content.

**Comment by Hypercubed** [comment]
Add the following:

```js
app.config(['markedProvider', function (markedProvider) {
  markedProvider.setOptions({sanitize: true});
}]);
```

Here is the plunker:  https://plnkr.co/edit/WpN3md

**Comment by rylyade1** [comment]
Hello, 
my bad. Sorry for that and thanks for the quick reply.
