### ISSUE TITLE
Automatic parsing when angular routes to .md file

### ISSUE THREAD

**Issue by Toilal** [Hypercubed/angular-marked#55]
Currently I have something like this

```javascript
  .config(function($routeProvider) {
    $routeProvider.when('/get-started', {
      'templateUrl' : 'get-started.html',
      'controller' : 'GetStartedCtrl',
      'controllerAs' : 'vm'
    })
```

with `get-started.html` containing only ```<marked src='get-started.md'></marked>```

It would be great to hook angular internals to automatically parse md files.

```javascript
  .config(function($routeProvider) {
    $routeProvider.when('/get-started', {
      'templateUrl' : 'get-started.md',
      'controller' : 'GetStartedCtrl',
      'controllerAs' : 'vm'
    })
```

I'm not sure it's feasible, and if it can support every router with a single codebase (ngRoute, UI Router, new router ...)

**Comment by Hypercubed** [comment]
You could probbably create a decorator for $route, something like this: https://github.com/Hypercubed/Project-Chi/blob/master/app/common/services/datapackage/index.js#L9

But I think the better option would be to inline the template:

```
  .config(function($routeProvider) {
    $routeProvider.when('/get-started', {
      'template' : '<marked src='get-started.md'></marked>'
    })
```

**Comment by Toilal** [comment]
Yes, inline template seems to be the way to go ! Thanks for the idea :)
