### ISSUE TITLE
cannot get marked to parse strings on a variable

### ISSUE THREAD

**Issue by ciel** [Hypercubed/angular-marked#57]
I have a controller that basically assigns text to a `$scope` variable like this;

````
$scope['Model'] = ["markdown text 1", "markdown text 2"];
````

And then I try to use `marked` on it within a view, like this;

````
<div ng-repeat="n in Model">
      <div marked="n"></div>
</div>
````

or 

````
<div marked>
   <div ng-repeat="n in Model">
         {{n}}
   </div>
</div>
````

I just get `{{n}}` as the output, verbatim. Marked never runs, never does anything to it. I'm completely baffled. I know the text is fine.

I have tried all of the examples and nothing seems to work. It does work if I put in static, hard-coded text between `<marked>` directives - but nothing dynamic.

The only way I've been able to make anything work is to forcefully use the `marked(n)` function within the controller - which is far less than ideal and certainly not what I'm wanting to do.

**Comment by Hypercubed** [comment]
I have no trouble with your first example.  See here:  http://plnkr.co/edit/tCaALb7rUnVchx8U9ZvL?p=preview

**Comment by Hypercubed** [comment]
If you are still having issues please create send an example and open again.  Thank you.

**Comment by ciel** [comment]
This turned out to be a faulty install from npm. I cleared out my npm cache and downloaded again, and it worked.
