### ISSUE TITLE
List of all supported Markdown syntax rules

### ISSUE THREAD

**Issue by SMerdzhanov** [Hypercubed/angular-marked#59]
Hi, I though that it would very useful if there is some sort of a list with all the supported syntax rules.

E.g.

# Supported syntax rules 

# Heading 1 
`# Heading 1`

## Heading 2
`# Heading 2`

### Heading 3
`# Heading 3`

etc.

I'm sorry if that's already being asked or answered somewhere, but I couldn't find any information. Even if all of the rules are supported you might want to include it as a *Note* somewhere in the GitHub Page.

Thank you :+1:

**Comment by Hypercubed** [comment]
Since this uses [marked](https://github.com/chjj/marked), any rules supported by marked are supported here.  Maybe some links from the readme to marked docs?  PRs welcome.

**Comment by Hypercubed** [comment]
Basically anything supported by marked is supported here... which I think is pretty much all markdown.  Closing.
