### ISSUE TITLE
html codespan and codeblock failing

### ISSUE THREAD

**Issue by wzr1337** [Hypercubed/angular-marked#6]
```
<marked>`<test>`</marked>
```

will result in
    ``

instead of:

    <test>

'marked' would parse correctly:

```
   marked.parse('`<test>`') ==> "<p><code>&lt;test&gt;</code></p>"
```
if you debug into your link function, you can already see, that the wrong string is handed over to marked.

**Comment by Hypercubed** [comment]
This is the same issue as #10 .  Now with v0.0.20 you can use a `src` attribute to load from a file or template.  This will process the markdown without striping tags in the code blocks.  If you need to have markdown in the same file use an `text/ng-template` script tag.  For example:

```
    <script type="text/ng-template" id="tpl.html">
      ## Tests
      
      *Some code*

      ```
      <test></test>
      ```
      
      **More test**
      
          This is <b>bold</b>
      
      **Additional**
      
      Star Trek & Star Wars
    </script>
    
    <div marked src="'tpl.html'"></div>
```

**Comment by Hypercubed** [comment]
Code blocks now work using the `src` attribute.  Thanks.  Closing.
