### ISSUE TITLE
Not able to load json markdown

### ISSUE THREAD

**Issue by akashnimare** [Hypercubed/angular-marked#60]
I am trying to use it with json data but it's not working. What method should I use here?

``` 
<div ng-repeat="row in user">
<h2><a  href="{{row.user.html_url}}" >{{row.user.login}}</h2></a>
 <marked> 
 {{row.body}} 
 </marked>  
 </div>

```

**Comment by Hypercubed** [comment]
<div marked="row.body"></div>

**Comment by akashnimare** [comment]
@Hypercubed Demo or it didn't happen :)

**Comment by Hypercubed** [comment]
This should work, if not please repoen.

**Comment by akashnimare** [comment]
It worked. Thanks a lot. We should add this in docs.

**Comment by Hypercubed** [comment]
It's in the [use as a directive](https://github.com/Hypercubed/angular-marked/blob/master/README.md#use-as-a-directive) section.  Any suggestions how to make it more clear?

**Comment by akashnimare** [comment]
Aha I think it's clear. Thanks.
