### ISSUE TITLE
hljs highlighting not working

### ISSUE THREAD

**Issue by HackerMD** [Hypercubed/angular-marked#61]
I've installed dependencies via bower

```
bower install marked
bower install angular-marked
bower install highlightjs
bower install angular-highlightjs
```

output of ``$ bower list``:

```
├─┬ angular-highlightjs#0.6.1
│ └── angular#1.5.5 (1.5.6-build.4831+sha.4a5723f available)
├─┬ angular-marked#1.2.0
│ ├── angular#1.5.5 (1.5.6-build.4831+sha.4a5723f available)
│ └── marked#0.3.5
├── marked#0.3.5
├── highlightjs#9.3.0 (latest is 9.4.0)
```

included the script tags

```html
"bower_components/highlightjs/highlight.pack.min.js"
"bower_components/angular-highlightjs/angular-highlightjs.min.js"
"bower_components/marked/lib/marked.js"
"bower_components/angular-marked/dist/angular-marked.min.js"
```
 
My app looks like this:

```javascript
var app = angular.module('app', ['hljs', 'hc.marked'])
.controller('my_controller', ['$scope', 'code', 'marked', function($scope, raw_text, marked) {
$scope.text = marked('```' + 'python' + '\n' + code + '\n' + '```');
}]);

app.config(['markedProvider', function (markedProvider) {
  markedProvider.setOptions({
    gfm: true,
    tables: true,
    highlight: function (code, lang) {
      if (lang) {
        return hljs.highlight(lang, code, true).value;
      } else {
        return hljs.highlightAuto(code).value;
      }
    }
  });
}]);
```

```html
<div ng-controller="my_controller"
    <div marked="text"></div>
</div>
```

However, I keep getting the `hljs` tags in the final html:

```html
<span class="hljs-keyword">
```

**Comment by Hypercubed** [comment]
A few things: 

1) Not sure how `angular-highlightjs` helps you here.  It should not be needed.
2) I assume teh missing closing bracket after `ng-controller="my_controller"` is a type:

```js
<div ng-controller="my_controller">
    <div marked="text"></div>
</div>
```

3) Your controller is using the marked service.  Which converts markdown to HTML.  Then you are using the marked directive, which does the same.   Use only the directive.

See here: https://plnkr.co/edit/ECnXqc

**Comment by HackerMD** [comment]
> Not sure how angular-highlightjs helps you here. It should not be needed.

Thought it might help. Removing it didn't help either, though.

> 2) I assume teh missing closing bracket after ng-controller="my_controller" is a type:

Sorry, just a typo.

> 3) Your controller is using the marked service. Which converts markdown to HTML. Then you are using the marked directive, which does the same. Use only the directive.

Thanks! This resolved the issues with the ``hljs`` tags. However, I still don't get any highlighting :(

**Comment by Hypercubed** [comment]
Make sure you are correctly installing hljs... including the CSS files.  See the plnkr above.

**Comment by Hypercubed** [comment]
If you still having issues reopen.  Thanks.
