### ISSUE TITLE
Unknown provider: hc.markedProvider

### ISSUE THREAD

**Issue by danielbair** [Hypercubed/angular-marked#62]
I've setup things this way:
```
	angular
		.module('i18n.hymns')
		.controller('HymnController', HymnController);

	HymnController.$inject = ['$stateParams', 'hymnsService', '$ionicActionSheet', '$cordovaSocialSharing', '$cordovaToast', '$scope', 'hc.marked'];

```
And I'm getting this:
"Error: [$injector:unpr] Unknown provider: hc.markedProvider <- hc.marked <- HymnController"

**Comment by Hypercubed** [comment]
`hc.marked` is the module, not something that can be injected.  See https://github.com/Hypercubed/angular-marked/blob/master/README.md#usage

**Comment by Hypercubed** [comment]
What you likely want is:

```js
    angular
        .module('i18n.hymns', ['hc.marked'])
        .controller('HymnController', HymnController);
```

**Comment by Hypercubed** [comment]
I'm going to close this.  If you still have issues please reopen.

**Comment by danielbair** [comment]
Yes, close it. I found https://github.com/vpegado/angular-markdown-filter
was able to do what I needed.

Thank you.


[image:
https://lh4.googleusercontent.com/-wIrA61rE_y4/AAAAAAAAAAI/AAAAAAAAAAA/EadW_TiIByg/s64-c/photo.jpg]
Daniel Bair, Director, Thailand Gospel Media Project
| m. 081-362-1520 | h. 817-264-6456 | o. 053-995-453
| e. missions@danielbair.com | w. missions.danielbair.com





On Mon, Jun 6, 2016 at 9:00 AM, Jayson Harshbarger <notifications@github.com
