### ISSUE TITLE
Use of ng-src

### ISSUE THREAD

**Issue by RandomHarlz** [Hypercubed/angular-marked#63]
Hey there, 
I don't know if I am missing something in front of my eyes or if angular-marked does not support this. But I have a page where depending on what button I click a different markdown file is loaded. There is a fairly large number of these which will change overtime, so writing it out manually is less than ideal. The way I would expect this to work is something like:
```
<div marked ng-src="/url/to/file/{{file_name}}.md"></div>
```
OR 
```
<div marked src="'/url/to/file/{{file_name}}.md'"></div>
```
However both of these break the whole page.
Any help would be greatly appreciated!

**Comment by Hypercubed** [comment]
The attribute is `src` which takes an expression.  The first example you gave is not an expression.  The second is but results in the string `'/url/to/file/{{file_name}}.md'`.  You need something like:

```
<div marked src="'/url/to/file/' + file_name + '.md'"></div>
```

Or better yet construct the whole url in the controller and move this logic out of the template.

**Comment by RandomHarlz** [comment]
When using the method you outlined above I get this error:
<pre>Error: [$interpolate:noconcat] http://errors.angularjs.org/1.5.5/$interpolate/noconcat?p0='%2Fviews%2Fdocs%2Fmarkdown%2F'%20%2B%20%7B%7Bdocs.info.name%7D%7D%20%2B%20'.md'
    at Error (native)
    at http://localhost:9000/bower_components/angular/angular.min.js:6:412
    at Function.Ja.throwNoconcat (http://localhost:9000/bower_components/angular/angular.min.js:209:85)
    at k (http://localhost:9000/bower_components/angular/angular.min.js:105:63)
    at fa (http://localhost:9000/bower_components/angular/angular.min.js:78:381)
    at x (http://localhost:9000/bower_components/angular/angular.min.js:60:397)
    at s (http://localhost:9000/bower_components/angular/angular.min.js:58:402)
    at s (http://localhost:9000/bower_components/angular/angular.min.js:59:55)
    at s (http://localhost:9000/bower_components/angular/angular.min.js:59:55)
    at s (http://localhost:9000/bower_components/angular/angular.min.js:59:55) </pre>

When I construct the whole url in the controller and use `ng-src="{{docs.info.md}}"` I receive no errors but no markdown is rendered. However, when examining the element it shows the correct file url and I can open the link to the `.md` file.

**Comment by Hypercubed** [comment]
I'm sorry, you are going to have to understand the difference between a template and an expression.   The curly brackets, in Angular, mean a template tag.  The attribute angular-marked uses is `src` (not `ng-src`) and it takes an expression.  Meaning no curly brackets.

That means `src="'some string'"` or `src="scopeVariable"`.  Never add curly brackets to an expression and don't use `ng-src` with Angular marked.

**Comment by RandomHarlz** [comment]
Ahh! Right! So sorry! It all makes sense now.
Much appreciated for your time.
