### ISSUE TITLE
Convert scope.marked to String before using it as a string

### ISSUE THREAD

**Issue by saharj** [Hypercubed/angular-marked#65]
As you can see in screenshot, `scope.marked` can be a number. 

<img width="415" alt="screen shot 2016-07-12 at 9 57 40 pm" src="https://cloud.githubusercontent.com/assets/1468463/16792281/04eb6922-487c-11e6-8f24-e6abf46656c3.png">

That happened by mistake in our code base but I am expecting angular-marked gracefully convert the value to string and then use it. 

This will throw because angular-marked is assuming `scope.marked` is string across the codebase.

**Comment by Hypercubed** [comment]
I think this is not going to work as implemented.  String(scope.marked) is truthy so the rest of the line is ignored.

Maybe something like.  If you can please run the tests.

```
if (scope.marked !== 'undefined') {
  set(String(scope.marked));
else {
  set(element.text() || '');
}
```

**Comment by saharj** [comment]
Updated my PR

**Comment by Hypercubed** [comment]
Sorry, I left off a bracket in my example. (before the else). If you are able to run the tests please do so before submitting.

**Comment by Hypercubed** [comment]
Hi @saharj,

I appreciate your contribution.  There is still a bug in your PR.  Can you see it?  Granted, in this case, it the bug is in my suggestion, however, it strongly suggested that you test PRs before you submit. 

Can't see the bug.  Here is a hint... when is `scope.marked === 'undefined'`?

**Comment by saharj** [comment]
`String(undefined)` returns `'undefined'`. that should be fine. 

I can't see it either. Although the original issue I opened is valid. Can you take a look yourself?

**Comment by Hypercubed** [comment]
I can fix it myself, but in order to give you full credit I'd like to merge a working PR.

`scope.marked === 'undefined'` is only true if `scope.marked` is the string `'undefined'`, not when the `marked` property is undefined.  I think we need:

```
if (typeof scope.marked === 'undefined') {
  set(element.text() || '');
} else {
  set(String(scope.marked));
}
```

**Comment by saharj** [comment]
Thank you for considering that. It's fine if you close this PR and push the fix yourself. :)

**Comment by saharj** [comment]
🎉
