### ISSUE TITLE
How to use markdown for a contentful entry

### ISSUE THREAD

**Issue by vergarm** [Hypercubed/angular-marked#67]
I'm using contentful which renders content similar to angularJS. Does this work If want to use it as a directive like below?
 `<marked>{{$contentfulEntry.fields.footerText}}</marked>`

Note that the content is pulled from a contentful repository. It's not coming from a $scope variable. How can I achieve this? Thanks

**Comment by Hypercubed** [comment]
Are you using angularJS and contentful?  I don't know anything about contentful.  If the `footerText` content is rendered on the server it should work.  Have you tried this?  You might investigate a non-angular solution, perhaps during server render.

**Comment by Hypercubed** [comment]
If you look at this again and think there is a bug please reopen.
