### ISSUE TITLE
Tables not rendering

### ISSUE THREAD

**Issue by jaydreyer** [Hypercubed/angular-marked#71]
I'm hoping this is something stupid. I can't get tables to render. I can get bold/italics/code/other markdown to render ok, but tables just show up like:

 | Type | Value | Necessity | | ------------ | ---------------- | --------- | | Content-Type | application/json | Required | | Accept | application/json | Required | | Accept | image/png | Optional | | Accept | image/gif | Optional | | Accept | image/jpeg | Optional |

I have tables: true in my app.js: 
```js
  .config(['markedProvider', function (markedProvider) {
    //Set the hc.marked options to render markdown to html
    markedProvider.setOptions({
      gfm: true,
      tables: true
    });
  }])
```

Any suggestions? Like I said, other markdown elements are working. I was thinking maybe none of the markdown was being rendered, but that's not the case.

Also, when I run the file I'm trying to render through a markdown previewer, the table displays perfectly.

**Comment by wkjesus** [comment]
i have the same issue

**Comment by jaydreyer** [comment]
OK. I figured it out. Turns out the system I work on was also using a markdown renderer on the back end, so the markdown that was pulled from a db was being converted to html before it even made it to marked. That was fun.

**Comment by Hypercubed** [comment]
I:m glad you were able to figure it out... sorry I didn't have a chance to look myself.
