### ISSUE TITLE
Could we support Angular2?

### ISSUE THREAD

**Issue by huan** [Hypercubed/angular-marked#73]
I'm trying to find a markdown directive in Angular2 today, if you could support angular2, that would be awesome.

It would be easy, here's a example: http://stackoverflow.com/a/36729417/1123955

**Comment by Hypercubed** [comment]
I've thought about it, but don't currently have a need for markdown component in ng 2+.

**Comment by huan** [comment]
Would you like to accept PR for it?

If so, I would like to make a PR  when I have time.

**Comment by Hypercubed** [comment]
Yes, please.

**Comment by Hypercubed** [comment]
I'm going to close this.  If we need an ngx markdown lib, it should be separate from this.
